### ISSUE TITLE
同步企业微信时,前端未处理506这个code,导致msg信息未弹出

### ISSUE THREAD

**Issue by peakliuz** [eryajf/go-ldap-admin-ui#26]
#### 您遇到了什么问题？ | What are your problems?
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/75781948/207504064-dc276f8a-fa26-462c-a33d-898ae6faeb12.png">

**Comment by eryajf** [comment]
本次优化集中针对这类问题进行了一波处理，参见：#29
