### ISSUE TITLE
前端npm install的时候异常，向一个以及被清空的库拉取数据

### ISSUE THREAD

**Issue by Wangyxiang** [eryajf/go-ldap-admin-ui#48]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 问题重现步骤 | 下载代码，npm install

**Comment by lonestep** [comment]
npm install --registry=http://registry.npmmirror.com
npm ERR! Cannot read property 'insert' of undefined
