### ISSUE TITLE
【镜像】阿里云拉不到镜像了

### ISSUE THREAD

**Issue by yunkaiOr2** [eryajf/go-ldap-admin-ui#55]
好像调整了镜像？ui项目的新镜像地址也更新下呗

**Comment by eryajf** [comment]
> 好像调整了镜像？ui项目的新镜像地址也更新下呗

最新版本调整了部署方案，前端已经集成到后端里边了，启动一个端口，即可同时访问后端与前端。

如果要拉这里前端最新的镜像，也是可以直接拉取的。

```
$ docker pull registry.cn-hangzhou.aliyuncs.com/eryajf/go-ldap-admin-ui
```

**Comment by yunkaiOr2** [comment]
> > 好像调整了镜像？ui项目的新镜像地址也更新下呗
> 
> 最新版本调整了部署方案，前端已经集成到后端里边了，启动一个端口，即可同时访问后端与前端。
> 
> 如果要拉这里前端最新的镜像，也是可以直接拉取的。
> 
> ```
> $ docker pull registry.cn-hangzhou.aliyuncs.com/eryajf/go-ldap-admin-ui
> ```

提示没权限。我试试新的部署方式
